### ISSUE TITLE
Chapter 5: Continued Evaluation - Class label consistency

### ISSUE THREAD

**Issue by mshearer0** [GoogleCloudPlatform/ml-design-patterns#12]
The order of the publications is inconsistent between the original CLASSES definition and the source name function:

CLASSES = {
    'github': 0,
    'nytimes': 1,
    'techcrunch': 2
}

labels = tf.constant(['github', 'techcrunch', 'nytimes'], dtype=tf.string)

Suggest:

labels = tf.constant(['github', 'nytimes','techcrunch'], dtype=tf.string)

**Comment by munnm** [comment]
Thanks for catching this. I've fixed it in the notebook.
